import 'package:atomic_habits_mobile/domain/models/habit.dart';
import '../constants/app_constants.dart';

/// Données d'exemple pour tester l'application
class SampleData {
  static List<Habit> getSampleHabits() {
    final now = DateTime.now();

    return [
      Habit(
        id: 1,
        name: 'Faire du sport',
        description: '30 minutes d\'exercice cardiovasculaire',
        category: 'Sport',
        frequency: 'Quotidien',
        identityStatement: 'Je suis un athlète',
        twoMinuteVersion: 'Mettre mes chaussures de sport',
        cue: 'Laisser mes chaussures près de mon lit',
        craving: 'Écouter ma playlist énergisante préférée',
        response: 'Faire 5 pompes pour démarrer la session',
        reward: 'Cocher ma liste et prendre une photo de mes progrès',
        reminderEnabled: true,
        reminderTime: '07:00',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now,
        currentStreak: 15,
        longestStreak: 21,
        totalCompletions: 25,
        color: 0xFFEF4444,
      ),

      Habit(
        id: 2,
        name: 'Lire 30 minutes',
        description: 'Lire des livres de développement personnel ou fiction',
        category: 'Apprentissage',
        frequency: 'Quotidien',
        identityStatement: 'Je suis un lecteur assidu',
        twoMinuteVersion: 'Lire une page',
        cue: 'Placer mon livre sur mon oreiller le soir',
        craving:
            'Me faire un thé et m\'installer dans mon fauteuil confortable',
        response: 'Commencer par une seule page',
        reward: 'Noter mes insights dans mon journal de lecture',
        reminderEnabled: true,
        reminderTime: '21:00',
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now,
        currentStreak: 8,
        longestStreak: 12,
        totalCompletions: 38,
        color: 0xFF3B82F6,
      ),

      Habit(
        id: 3,
        name: 'Méditation matinale',
        description: 'Pratiquer la pleine conscience',
        category: 'Mindfulness',
        frequency: 'Quotidien',
        identityStatement: 'Je suis quelqu\'un de calme et présent',
        twoMinuteVersion: 'Prendre trois respirations profondes',
        cue: 'Alarme sur mon téléphone à 6h45',
        craving:
            'Utiliser mon coussin de méditation préféré et allumer une bougie',
        response: 'Commencer par seulement 2 minutes',
        reward: 'Marquer mon calendrier avec une étoile dorée',
        reminderEnabled: true,
        reminderTime: '06:45',
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
        currentStreak: 22,
        longestStreak: 30,
        totalCompletions: 52,
        color: 0xFF6366F1,
      ),

      Habit(
        id: 4,
        name: 'Apprendre le français',
        description: 'Étudier le vocabulaire et la grammaire',
        category: 'Apprentissage',
        frequency: 'Quotidien',
        identityStatement: 'Je suis quelqu\'un qui apprend constamment',
        twoMinuteVersion: 'Réviser 3 mots de vocabulaire',
        cue: 'Ouvrir l\'application Duolingo après le petit-déjeuner',
        craving: 'Gagner des points et maintenir ma série',
        response: 'Faire une leçon de 5 minutes minimum',
        reward: 'Célébrer mes XP gagnés et partager mes progrès',
        reminderEnabled: true,
        reminderTime: '08:30',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now,
        currentStreak: 12,
        longestStreak: 15,
        totalCompletions: 18,
        color: 0xFF3B82F6,
      ),

      Habit(
        id: 5,
        name: 'Boire 2L d\'eau',
        description: 'Rester bien hydraté tout au long de la journée',
        category: 'Santé',
        frequency: 'Quotidien',
        identityStatement: 'Je suis quelqu\'un qui prend soin de sa santé',
        twoMinuteVersion: 'Remplir ma bouteille d\'eau',
        cue: 'Placer ma bouteille d\'eau sur mon bureau',
        craving: 'Utiliser ma belle bouteille en verre',
        response: 'Boire un verre d\'eau toutes les heures',
        reward: 'Cocher chaque verre sur mon tracker',
        reminderEnabled: false,
        createdAt: now.subtract(const Duration(days: 10)),
        updatedAt: now,
        currentStreak: 5,
        longestStreak: 7,
        totalCompletions: 8,
        color: 0xFFEC4899,
      ),

      Habit(
        id: 6,
        name: 'Journal de gratitude',
        description: 'Noter 3 choses pour lesquelles je suis reconnaissant',
        category: 'Mindfulness',
        frequency: 'Quotidien',
        identityStatement: 'Je suis quelqu\'un de reconnaissant',
        twoMinuteVersion:
            'Écrire une chose pour laquelle je suis reconnaissant',
        cue: 'Laisser mon journal sur ma table de nuit',
        craving: 'Utiliser mon stylo préféré et mon beau journal',
        response: 'Noter juste une chose au minimum',
        reward: 'Ressentir la gratitude et la paix intérieure',
        reminderEnabled: true,
        reminderTime: '22:00',
        createdAt: now.subtract(const Duration(days: 35)),
        updatedAt: now,
        currentStreak: 18,
        longestStreak: 25,
        totalCompletions: 32,
        color: 0xFF6366F1,
      ),

      Habit(
        id: 7,
        name: 'Appeler un proche',
        description: 'Rester en contact avec ma famille et mes amis',
        category: 'Social',
        frequency: 'Hebdomadaire',
        identityStatement: 'Je suis quelqu\'un qui cultive ses relations',
        twoMinuteVersion: 'Envoyer un message à un proche',
        cue: 'Mettre un rappel dans mon calendrier le dimanche',
        craving: 'Profiter d\'un bon moment de connexion',
        response: 'Appeler pendant ma pause café',
        reward: 'Sentir la connexion et l\'amour partagé',
        reminderEnabled: true,
        reminderTime: '14:00',
        createdAt: now.subtract(const Duration(days: 14)),
        updatedAt: now,
        currentStreak: 2,
        longestStreak: 3,
        totalCompletions: 2,
        color: 0xFF10B981,
      ),

      Habit(
        id: 8,
        name: 'Coder 1h',
        description: 'Travailler sur mes projets de programmation',
        category: 'Productivité',
        frequency: 'Quotidien',
        identityStatement: 'Je suis un développeur compétent',
        twoMinuteVersion: 'Ouvrir VS Code et lire le code',
        cue: 'Bloquer 1h dans mon agenda le matin',
        craving: 'Travailler sur un projet qui me passionne',
        response: 'Commencer par corriger un petit bug',
        reward: 'Commit mes changements et voir ma contribution',
        reminderEnabled: true,
        reminderTime: '09:00',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now,
        currentStreak: 10,
        longestStreak: 14,
        totalCompletions: 20,
        color: 0xFF8B5CF6,
      ),
    ];
  }

  static String getRandomQuote() {
    return AppConstants.quotes[DateTime.now().day % AppConstants.quotes.length];
  }
}
